### ISSUE TITLE
Handle multiple cookie values sent in a request

### ISSUE THREAD

**Issue by Ptrskay3** [maxcountryman/axum-sessions#1]
First of all, thank you for making this lib.

I noticed that when multiple cookies sent in a request, it's not parsed correctly. For example with this cookie
```
first=asdf; axum.sid=1234
```
currently the `name()` of the cookie is `first`, and the `value` is `asdf; axum.sid=1234`, thus it fails to identify the `session_layer.cookie_name` is actually present.

The relevant part of the code is:
```rust
 let cookie_value = request
            .headers()
            .get(COOKIE)
            .and_then(|cookie| Cookie::parse_encoded(cookie.to_str().unwrap()).ok())
            .filter(|cookie| cookie.name() == session_layer.cookie_name)
            .and_then(|cookie| session_layer.verify_signature(cookie.value()).ok());
```

I think something like this should work (please check, I haven't tested this very thoroughly).
```rust
        let cookie_values = request
            .headers()
            .get(COOKIE)
            .map(|cookies| cookies.to_str());

        let cookie_value = if let Some(Ok(cookies)) = cookie_values {
            cookies
                .split(";")
                .map(|cookie| cookie.trim())
                .filter_map(|cookie| Cookie::parse_encoded(cookie).ok())
                .filter(|cookie| cookie.name() == session_layer.cookie_name)
                .find_map(|cookie| self.layer.verify_signature(cookie.value()).ok())
        } else {
            None
        };
```
Let me know what do you think about it.

**Comment by maxcountryman** [comment]
Thanks for pointing this out. I'd be happy to fix this. Would you be interested in submitting a PR?

**Comment by maxcountryman** [comment]
Version `0.1.1` is now available and includes this change.
