### ISSUE TITLE
Idea: Rework session service implementation to use the new axum 0.6 state pattern

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/axum-sessions#16]
As mentioned [here](https://tokio.rs/blog/2022-11-25-announcing-axum-0-6-0) and explained in more detail [here](https://docs.rs/axum/latest/axum/middleware/index.html#accessing-state-in-middleware).

**Comment by Ptrskay3** [comment]
Correct me if I'm wrong, but `State` is for global application resources, which is the same for _all_ requests, such as database pools or email clients. On the other hand though, the session we add as an extension to the request is local, and differ from request to request.

**Comment by maxcountryman** [comment]
Yes, I think you are right. (It's a bit confusing how the new middleware docs mention state now.)

That said, while this has no practical bearing on things (it does not provide additional type safety, for example), I did [reorganize the `axum-login` middleware a bit](https://github.com/maxcountryman/axum-login/blob/53e382dd6eb14a03dd1aa05385b3127a37797690/src/auth.rs#L23-L28).

We could potentially do something similar here but again I don't think it makes much of a difference in practice.

**Comment by maxcountryman** [comment]
Closing this for now.
