### ISSUE TITLE
Please consider to keep a changelog

### ISSUE THREAD

**Issue by LeoniePhiline** [maxcountryman/axum-sessions#18]
This is a great start: https://keepachangelog.com/en/1.1.0/ 

GitHub Releases like https://github.com/LeoniePhiline/axum-csrf-sync-pattern/releases also would help dependents know what changed per each release!

Thanks for your consideration.

**Comment by maxcountryman** [comment]
Thanks for raising this. I think it would be nice to start using tools like cargo release in conjunction with this.

**Comment by LeoniePhiline** [comment]
Once you did, I'll copy yours ;)

**Comment by maxcountryman** [comment]
Should be addressed by: https://github.com/maxcountryman/axum-sessions/commit/d7b96f93ca1dca62f96d5e972fc3260d82d7da15

**Comment by LeoniePhiline** [comment]
Thank you! 💛
