### ISSUE TITLE
Resist session id name fingerprinting by default

### ISSUE THREAD

**Issue by LeoniePhiline** [maxcountryman/axum-sessions#24]
The default session cookie name gives away that axum (or this specific middleware) is used:

https://github.com/maxcountryman/axum-sessions/blob/main/src/session.rs#L112

This should be changed to a generic default, like `sid`, `id`, or `ses`. 

See also:

https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-id-name-fingerprinting

**Comment by maxcountryman** [comment]
Good find! Let's change it.

**Comment by maxcountryman** [comment]
I believe this was addressed in #36.
