### ISSUE TITLE
Rustdoc code doesn't compile due to minor import error

### ISSUE THREAD

**Issue by tekul** [maxcountryman/axum-sessions#25]
[This line in lib.rs](https://github.com/maxcountryman/axum-sessions/blob/d1dc89c65da20a9018f86b3800a5a3a81f85ced9/src/lib.rs#L25) needs the `async_session` module name removed since `MemoryStore` is imported directly. The same example in the README is already correct.

**Comment by maxcountryman** [comment]
Is this still an issue?

**Comment by tekul** [comment]
Looks like it. I created a PR #45 to make it the same as the README. I'm not sure why the doctest  example works in that file though, which was doing the same thing (possibly because the crate re-exposes `async_session` at the top level?). It definitely doesn't work when I copy it in an app though - just a basic Rust import issue.
