### ISSUE TITLE
Session not saving when returning a redirect response

### ISSUE THREAD

**Issue by ashahid05** [maxcountryman/axum-sessions#26]
Basically the issue is that I have an endpoint (lets call it auth endpoint) that fetches some data from a 3rd party application and based on the response from that app if it's successful it inserts key `signed_in` into a session, then the client is redirected to another endpoint (lets call it data endpoint). and from inside that other endpoint when i try to read the session it says that the key `signed_in` is `None`, this is the issue. but when the auth endpoint sends a response back without redirecting.. it saves the session successfully and when i navigate to the data endpoint it reads the session correctly.

Excuse me for my rusty English and my terrible explanation but I hope you get the idea.

Edit:
Here is a better explanation

the issue
```rs
fn auth_endpoint(mut session: WriteableSession) {
    do_some_logic();
    session.insert("signed_in", true).unwrap();
    return Redirect::to("/data-endpoint");
}

fn data_endpoint(session: ReadableSession) {
    let signed_in = session.get::<bool>("signed_in").unwrap_or(false);
    // signed_in is None (false)
}
```

The walk-around
```rs
fn auth_endpoint(mut session: WriteableSession) {
    do_some_logic();
    session.insert("signed_in", true).unwrap();
    return "OK!"
}
// then when a user manually navigates to this /data-endpoint
fn data_endpoint(session: ReadableSession) {
    let signed_in = session.get::<bool>("signed_in").unwrap_or(false);
    // signed_in is true
}
```

Is there a way i can fix this or am i doing something wrong?

**Comment by maxcountryman** [comment]
Thanks for raising this. Would you mind putting together an example following the format of our examples directory? (The easiest way is probably to fork this repo and create a new example in that directory.) This will allow me to inspect what you're seeing more directly.

**Comment by ashahid05** [comment]
Hi again, I've tried to reproduce this issue but it turns out to work, I've tried to debug and do everything I thought of in the project I am working on but nothing has fixed the issue, I still do not know whats causing it.. Even though everything in the reproduced repo is pretty much the same as the project I'm working on but it's really messed up..

**Comment by maxcountryman** [comment]
Sorry you're running into that. That's frustrating. 

Have you checked that the crates are all the same versions between the two?

**Comment by ashahid05** [comment]
I've sent you an invite to the repository, thanks much!

**Comment by vkill** [comment]
Require `.with_same_site_policy(SameSite::Lax)` and `.with_secure(false)`

**Comment by maxcountryman** [comment]
@vkill in production, I would advise setting secure to `true`.
