### ISSUE TITLE
Type-safe `Session` handles

### ISSUE THREAD

**Issue by avdb13** [maxcountryman/axum-sessions#42]
Since Axum 6.0 it's possible to use `State` instead of `Extension` to avoid runtime errors (see https://github.com/tokio-rs/axum/pull/1155). I was wondering if the same could possibly be implemented for `ReadableSession`/`WritableSession`.

**Comment by maxcountryman** [comment]
I'm not sure it's possible to use `State` in a library. Previous discussion: https://github.com/maxcountryman/axum-sessions/issues/16
