### ISSUE TITLE
Implementing `MemoryStore`

### ISSUE THREAD

**Issue by BurntNail** [maxcountryman/axum-sessions#44]
Hey,

I'm trying to write a custom [`MemoryStore`](https://docs.rs/async-session/3.0.0/async_session/struct.MemoryStore.html) that works with a [`sqlx`](https://lib.rs/crates/sqlx) postgres database to store sessions for [`axum-login`](https://lib.rs/crates/axum-login).
I've got the following SQL, which has space for all the non-serde-skipped parts of [`Session`](https://docs.rs/async-session/3.0.0/async_session/struct.Session.html):
```sql
CREATE TABLE auth_sessions (
    id TEXT PRIMARY KEY NOT NULL,
    expiry TIMESTAMP
);

CREATE TABLE auth_session_data (
    k TEXT NOT NULL,
    v TEXT NOT NULL,

    session_id TEXT NOT NULL,
    CONSTRAINT fk_session_id
        FOREIGN KEY (session_id)
        REFERENCES auth_sessions(id)
        ON DELETE CASCADE
)
```

Unfortunately, I can't work out a way to get the session contents to/from SQL, as I can't seem to find a constructor for making a `Session`, or getting all of the data - I can get values from keys but if I don't know what keys are being used (and would rather not have to hardcode a list from `axum-login`), and I can make a new cookie and add data but I can't do things like set the ID.

**Comment by BurntNail** [comment]
Apologies, I should've taken this to async-session.

**Comment by BurntNail** [comment]
> Is there a reason you aren’t using the provided sqlx stores?

Correct me if I'm wrong @maxcountryman, but looking at the docs.rs pages (for [sqlxstore](https://docs.rs/axum-login/latest/axum_login/struct.SqlxStore.html) and the concrete [postgresstore](https://docs.rs/axum-login/latest/axum_login/type.PostgresStore.html)), it only looks like implement `UserStore` and not `SessionStore`?

**Comment by maxcountryman** [comment]
You can just that in conjunction with `axum-session` which also supports `sqlx`. Check out the examples.

**Comment by BurntNail** [comment]
Ah OK, so I should just be using the `serde` fields and a deserialiser/representation like JSON. Thanks!
