### ISSUE TITLE
Memory session is not persisted (on RPi Arm)

### ISSUE THREAD

**Issue by maciekglowka** [maxcountryman/axum-sessions#46]
Hi, I have an issue with the memory session.
It works when I am testing on Ubuntu at x64, however it does not on Arm Raspberry.

I am using a simple password only `authentication` to protect the view with the `MemoryStore`:

```rust
let store = MemoryStore::new();
let secret = rand::thread_rng().gen::<[u8; 128]>();
let session_layer = SessionLayer::new(store, &secret);
```
(i guess it is straight from the examples)

Then in my login endpoint I simply do:
```rust
session.insert("auth", true)
        .expect("Session write error!");
```
And the expect is not called - so the session mechanism works. (which I confirmed by printing it to the console at this point).

But, when I try to read the session in the protected endpoint I get a `None` value:

```rust
    if !session.get("auth").unwrap_or(false) {
        return Redirect::to("/login").into_response();
    }
```
(on Raspbian, on Ubuntu it is fine - I get the proper session state)

I am not sure if the issue is not coming from the `async-session` crate - but have no idea at the moment how to figure it out.
I wonder what are the differences between those platforms that can cause that. I mean probably on the Pi the memory state is dropped or not properly shared between the async calls (?)

**Comment by czocher** [comment]
You may want to try to set a debug brakepoint after the `insert` call and check if the memory is modified. Then another one next to the `get` and check if the same memory is read.

**Comment by maxcountryman** [comment]
> let secret = rand::thread_rng().gen::<[u8; 128]>();

This generates a new secret upon each run of the application--this probably isn't what you want if you plan to restart the process and continue with prior sessions.

**Comment by maxcountryman** [comment]
Please let us know if setting your secret to a static value does not resolve this, otherwise I'll close this for now.
