### ISSUE TITLE
Bug: data present in session, but `.get` returns `None`

### ISSUE THREAD

**Issue by DrewMcArthur** [maxcountryman/axum-sessions#48]
<img width="1384" alt="Screenshot 2023-07-20 at 4 42 19 PM" src="https://github.com/maxcountryman/axum-sessions/assets/5150297/3cb7bcaa-e127-45f5-bc9a-244988fffff3">
<img width="1106" alt="Screenshot 2023-07-20 at 4 43 07 PM" src="https://github.com/maxcountryman/axum-sessions/assets/5150297/b68a773e-46eb-4370-8264-8b73aa86aaed">

first screenshot: you can see in the left pane that `string` is populated with some stringified json, but in the
second screenshot: the result of `session.get(key)` is `None`.  you can also see the data is available inside the session variable.

it may be (likely) that the serde_json::to_string is failing, but i have no visibility into that due to the `.ok()` here, which throws out the error.

IMO, `Session::get` should return `Result<Option<T>,Err>`, to distinguish between three possible states:
- the requested key doesn't have any data in the session store: `Ok(None)`
- the requested data: `Ok(Some(data))`
- the key does have data, but there was an error getting it to you: `Err(...)`

**Comment by DrewMcArthur** [comment]
shoot, didn't look closely and only just noticed that this is in `async-session`, not your crate.  my bad!

**Comment by maxcountryman** [comment]
@DrewMcArthur I'm working on a replacement for `axum-sessions` that implements its own session: https://github.com/maxcountryman/tower-sessions. Feedback appreciated. 🙂
