### ISSUE TITLE
WritableSession Load Forever

### ISSUE THREAD

**Issue by indpurvesh** [maxcountryman/axum-sessions#49]
i am having some issue with axum-sessions. WritableSession is just loading forever. But same Wrirable session works in my 3 handler function but for weird reason it just does not in one of my handler.

Does not work handler

 ```
pub async fn store_admin_user_handler(  
    mut session: WritableSession,  
    app_state: State<Arc<AppState>>,  
    Form(payload): Form<StoreAdminUserRequest>,  
 ) -> Result<impl IntoResponse, impl IntoResponse> { 
       Ok(Json(json!({})).into_response())  
  }
```
Below handler it works perfectly fine.

```
 pub async fn post_admin_login_handler(
     mut session: WritableSession,
     app_state: State<Arc<AppState>>,
     Form(payload): Form<LoginAdminUserRequest>,
 ) -> Result<impl IntoResponse, impl IntoResponse> { 
    Ok(Json(json!({})).into_response())  
  }
```

**Comment by Kokonoeqt** [comment]
> i am having some issue with axum-sessions. WritableSession is just loading forever. But same Wrirable session works in my 3 handler function but for weird reason it just does not in one of my handler.
> 
> Does not work handler
> 
> ```
> pub async fn store_admin_user_handler(  
>    mut session: WritableSession,  
>    app_state: State<Arc<AppState>>,  
>    Form(payload): Form<StoreAdminUserRequest>,  
> ) -> Result<impl IntoResponse, impl IntoResponse> { 
>       Ok(Json(json!({})).into_response())  
>  }
> ```
> 
> Below handler it works perfectly fine.
> 
> ```
>  pub async fn post_admin_login_handler(
>      mut session: WritableSession,
>      app_state: State<Arc<AppState>>,
>      Form(payload): Form<LoginAdminUserRequest>,
>  ) -> Result<impl IntoResponse, impl IntoResponse> { 
>     Ok(Json(json!({})).into_response())  
>   }
> ```

Omg I wish I seen this, I am literally facing same issue and was thinking of dropping the lock myself but if I have to manage the lock myself for more than one writable/readable session then I think it might be design issue?

Currently I have to do something like:

```rust
pub async fn auth_middleware_cookie<B>(
    State(state): State<AppState>,
    request: Request<B>,
    next: Next<B>,
) -> Response {
    tracing::info!("Auth middleware cookie");

    let session_handle = request.extensions().get::<SessionHandle>().unwrap().clone();

    tracing::info!("About to read from session handle");
    let session = session_handle.read().await;
    tracing::info!("Read from session handle completed");
    
    drop(session);
    tracing::info!("Calling next middleware");
    let response = next.run(request).await;
    tracing::info!("Response: {:?}", response);
    response
}
```

If I don't have the drop(session) it just never goes to the handler and hangs there causing it to timeout.

**Comment by maxcountryman** [comment]
Please see #50.

**Comment by indpurvesh** [comment]
@maxcountryman  thanks for it. I did see that PR. Good works
